<ul class="list-inline list-unstyled">
    <li><a href=""><?php echo $this->__('Home'); ?></a></li>
    <li><a href=""><?php echo $this->__('About'); ?></a></li>
    <li><a href=""><?php echo $this->__('Customer Service'); ?></a></li>
    <li><a href=""><?php echo $this->__('Site Map'); ?></a></li>
    <li><a href=""><?php echo $this->__('Search Terms'); ?></a></li>
    <li><a href=""><?php echo $this->__('Contacts'); ?></a></li>
</ul>