<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="header-top">
                <div class="pull-left">
                    <?php echo $this->getChildHtml('header-registration-top-links'); ?>
                </div>
                <div class="pull-right">
                    <?php echo $this->getChildHtml('store_language'); ?>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="header-links">
                <div class="pull-left log-text">
                    <?php echo $this->getChildHtml('welcome'); ?>
                </div>
                <div class="pull-right header-menu-top-links">
                    <?php echo $this->getChildHtml('header-menu-top-links'); ?>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="header-content">
                <div class="row">
                    <div class="col-md-2 header-logo">
                        <div class="logo">
                            <p class="text-center">LP</p>
                        </div>
                    </div>
                    <div class="col-md-10 header-search-menu">
                        <div class="search">
                            <?php echo $this->getChildHtml('topSearch'); ?>
                        </div>
                        <div class="main-menu">
                            <?php echo $this->getChildHtml('topMenu'); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>