<div class="container">
    <div class="row home-page-first-line">
        <div class="col-md-8">
            <img src="<?php echo $this->getSkinUrl('images/new-collection.png'); ?>"/>
        </div>
        <div class="col-md-4">
            <div class="img-b2">
                <img src="<?php echo $this->getSkinUrl('images/b2.png'); ?>"/>
            </div>
            <div class="img-shoes">
                <img src="<?php echo $this->getSkinUrl('images/shoes.png'); ?>"/>
            </div>
        </div>
    </div>
    <div class="row home-page-second-line">
        <div class="col-md-4">
            <div class="free-shipping">
            </div>
        </div>
        <div class="col-md-8">
            <img src="<?php echo $this->getSkinUrl('images/dresses.png'); ?>"/>
        </div>
    </div>
</div>