<div class="container">
    <div class="row">
        <div class="col-md-8">
            <img src="<?php echo $this->getSkinUrl('images/new-collection.png'); ?>"/>
        </div>
        <div class="col-md-4">
            <img src="<?php echo $this->getSkinUrl('images/b2.png'); ?>"/>
            <img src="<?php echo $this->getSkinUrl('images/shoes.png'); ?>"/>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="free-shipping">

            </div>
        </div>
        <div class="col-md-8">
            <img src="<?php echo $this->getSkinUrl('images/dresses.png'); ?>"/>
        </div>
    </div>
</div>