<h3><?php echo $this->__('Why buy from us'); ?></h3>
<ul class="list-unstyled">
    <li><a href=""><?php echo $this->__('Shipping & Returns'); ?></a></li>
    <li><a href=""><?php echo $this->__('Secure Shopping'); ?></a></li>
    <li><a href=""><?php echo $this->__('International Shipping'); ?></a></li>
    <li><a href=""><?php echo $this->__('Affiliates'); ?></a></li>
    <li><a href=""><?php echo $this->__('Group Sales'); ?></a></li>
</ul>