<h3><?php echo $this->__('Contacts'); ?></h3>
<ul class="list-unstyled">
    <li><a href="">linkf3</a></li>
    <li><a href="">linkf3</a></li>
    <li><a href="">linkf3</a></li>
    <li><a href="">linkf3</a></li>
    <li><a href="">linkf3</a></li>
</ul>
<h4><?php echo $this->__('Tel'); ?>: 1(245)587-36-56</h4>
<ul class="list-inline list-unstyled">
    <li><a href="">linkf3</a></li>
    <li><a href="">linkf3</a></li>
    <li><a href="">linkf3</a></li>
</ul>