<h3><?php echo $this->__('Contacts'); ?></h3>
<ul class="list-unstyled">
    <li><a href=""><?php echo $this->__('38 Anson Road'); ?></a></li>
    <li><a href=""><?php echo $this->__('Martlesham Heath'); ?></a></li>
</ul>
<h4 class="footer-tel"><?php echo $this->__('Tel'); ?>: 1(245)587-36-56</h4>
<ul class="list-inline list-unstyled">
    <li><a href=""><img src="<?php echo $this->getSkinUrl('images/Layer-8.png'); ?>"/></a></li>
    <li><a href=""><img src="<?php echo $this->getSkinUrl('images/Layer-9.png'); ?>"/></a></li>
    <li><a href=""><img src="<?php echo $this->getSkinUrl('images/Layer-10.png'); ?>"/></a></li>
</ul>