<h3><?php echo $this->__('Information'); ?></h3>
<ul class="list-unstyled">
    <li><a href=""><?php echo $this->__('About Us'); ?></a></li>
    <li><a href=""><?php echo $this->__('Customer Service'); ?></a></li>
    <li><a href=""><?php echo $this->__('privacy Policy'); ?></a></li>
    <li><a href=""><?php echo $this->__('Site Map'); ?></a></li>
    <li><a href=""><?php echo $this->__('Search Terms'); ?></a></li>
    <li><a href=""><?php echo $this->__('Advanced Search'); ?></a></li>
    <li><a href=""><?php echo $this->__('Orders And Returns'); ?></a></li>
    <li><a href=""><?php echo $this->__('Contact Us'); ?></a></li>
</ul>