<h3><?php echo $this->__('My account'); ?></h3>
<ul class="list-unstyled">
    <li><a href=""><?php echo $this->__('Sign In'); ?></a></li>
    <li><a href=""><?php echo $this->__('View Cart'); ?></a></li>
    <li><a href=""><?php echo $this->__('My Wishlist'); ?></a></li>
    <li><a href=""><?php echo $this->__('Track My Order'); ?></a></li>
    <li><a href=""><?php echo $this->__('Help'); ?></a></li>
</ul>