<?php
/* @var $this Mage_Core_Block_Template */
/* @var $catalogSearchHelper Mage_Catalogsearch_Helper_Data */
$catalogSearchHelper =  $this->helper('catalogsearch');
?>

<form id="search_mini_form" class="form-horizontal" action="<?php echo $catalogSearchHelper->getResultUrl() ?>" method="get">
    <div class="form-group header-search-form">
        <div class="col-md-10 header-form-search-input">
            <input id="search" type="search" class="form-control header-form-input" name="<?php echo $catalogSearchHelper->getQueryParamName() ?>" value="<?php echo $catalogSearchHelper->getEscapedQueryText() ?>" class="input-text required-entry" maxlength="<?php echo $catalogSearchHelper->getMaxQueryLength();?>" placeholder="<?php echo $this->__('Search entire store here...') ?>" />
        </div>
        <div class="col-md-2 header-form-search-submit">
            <button type="submit" title="<?php echo $this->__('Search') ?>" class="btn btn-default header-form-btn-search">
                <?php echo $this->__('Search'); ?>
            </button>
        </div>
    </div>

    <div id="search_autocomplete" class="search-autocomplete"></div>
    <script type="text/javascript">
        //<![CDATA[
        var searchForm = new Varien.searchForm('search_mini_form', 'search', '');
        searchForm.initAutocomplete('<?php echo $catalogSearchHelper->getSuggestUrl() ?>', 'search_autocomplete');
        //]]>
    </script>
</form>